Instructor.create(name: 'nick', email: 'nicksolony@gmail.com', password: '1', first_name:'Nick', last_name:'Solony', phone:'347-691-2935')
Instructor.create(name: 'anna', email: 'savanna@gmail.com', password: '1', first_name:'Anna', last_name:'Savkina', phone:'212-343-1111')
Instructor.create(name: 'scott', email: 'scottw@next.com', password: '1', first_name:'Scott', last_name:'Wolf', phone:'212-222-3333')
Instructor.create(name: 'peter', email: 'peterst@yahoo.com', password: '1234', first_name:'Peter', last_name:'Night', phone:'112-234-1232')
Instructor.create(name: 'michelle', email: 'msmith@teast.com', password: '1234', first_name:'Michelle', last_name:'Smith', phone:'787-898-6653')
CourseGroup.create(name: 'Excel', creator_id: 1)
CourseGroup.create(name: 'Ruby', creator_id: 3)
CourseGroup.create(name: 'SQL', creator_id: 1)
CourseGroup.create(name: 'PowerPoint', creator_id: 1)
CourseGroup.create(name: 'QuickBooks', creator_id: 5)
CourseGroup.create(name: 'InDesign', creator_id: 2)
CourseGroup.create(name: 'Photoshop', creator_id: 2)
CourseGroup.create(name: 'Illustrator', creator_id: 2)

Course.create(name: 'Excel Level 1', course_length: 6, course_description: 'Beginner Excel Course',creator_id: 1, course_group_id: 1)
Course.create(name: 'Excel Level 2', course_length: 6, course_description: 'Intermediate Excel Course',creator_id: 1, course_group_id: 1)
Course.create(name: 'Excel Level 3', course_length: 6, course_description: 'Advanced Excel Course',creator_id: 1, course_group_id: 1)
Course.create(name: 'Intro to Ruby', course_length: 6, course_description: 'Introduction to Ruby',creator_id: 3, course_group_id: 2)
Course.create(name: 'SQL Level 1', course_length: 6, course_description: 'Introduction to SQL Server',creator_id: 1, course_group_id: 3)
Course.create(name: 'SQL Level 2', course_length: 6, course_description: 'Advanced Course in SQL Server',creator_id: 3, course_group_id: 3)
Course.create(name: 'PowerPoint for Beginners', course_length: 6, course_description: 'Intro to PowerPoint',creator_id: 1, course_group_id: 4)
Course.create(name: 'Animation in PowerPoint', course_length: 3, course_description: 'Learn how to animate in PPT',creator_id: 2, course_group_id: 4)
Course.create(name: 'QuickBooks Desktop', course_length: 6, course_description: 'Learn how to use QuickBooks on PC',creator_id: 5, course_group_id: 5)
Course.create(name: 'QuickBooks Online', course_length: 6, course_description: 'Learn QuickBooks Online in this 1 day class',creator_id: 5, course_group_id: 5)
Course.create(name: 'InDesign for Beginners', course_length: 6, course_description: 'Basic InDesign Class',creator_id: 2, course_group_id: 6)
Course.create(name: 'Photoshop for Beginners', course_length: 6, course_description: 'Basic Photoshop Class',creator_id: 2, course_group_id: 7)
Course.create(name: 'Illustrator for Beginners', course_length: 6, course_description: 'Basic Illustrator Class',creator_id: 2, course_group_id: 8)

InstructorCourse.create(instructor_id: 1, course_id: 1)
InstructorCourse.create(instructor_id: 1, course_id: 2)
InstructorCourse.create(instructor_id: 1, course_id: 3)
InstructorCourse.create(instructor_id: 3, course_id: 4)
InstructorCourse.create(instructor_id: 1, course_id: 5)
InstructorCourse.create(instructor_id: 3, course_id: 6)
InstructorCourse.create(instructor_id: 1, course_id: 7)
InstructorCourse.create(instructor_id: 2, course_id: 8)
InstructorCourse.create(instructor_id: 5, course_id: 9)
InstructorCourse.create(instructor_id: 5, course_id: 10)
InstructorCourse.create(instructor_id: 2, course_id: 11)
InstructorCourse.create(instructor_id: 2, course_id: 12)
InstructorCourse.create(instructor_id: 2, course_id: 13)
InstructorCourse.create(instructor_id: 4, course_id: 5)
InstructorCourse.create(instructor_id: 4, course_id: 6)
InstructorCourse.create(instructor_id: 4, course_id: 1)
InstructorCourse.create(instructor_id: 4, course_id: 2)
InstructorCourse.create(instructor_id: 4, course_id: 3)
InstructorCourse.create(instructor_id: 1, course_id: 4)
InstructorCourse.create(instructor_id: 3, course_id: 5)
InstructorCourse.create(instructor_id: 3, course_id: 6)
InstructorCourse.create(instructor_id: 3, course_id: 1)
InstructorCourse.create(instructor_id: 3, course_id: 2)
InstructorCourse.create(instructor_id: 3, course_id: 3)
